"""
train_phase8_uncertainty.py

This script implements a self-training strategy to expand the dataset using pseudo-labels
generated by a teacher model. It then builds and trains a student model consisting of a
Convolutional Block Attention Module (CBAM) integrated into a CNN architecture. The student
model is trained on the expanded dataset and evaluated for classification accuracy.
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, backend as K
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils import class_weight
import cv2
import pickle
import os


# --- CBAM Block Implementation ---
def cbam_block(input_tensor, ratio=8):
    """
    Convolutional Block Attention Module (CBAM)
    """
    # 1. Channel Attention Module
    channel_axis = -1
    channels = input_tensor.shape[channel_axis]

    # Shared Dense layers
    dense1 = layers.Dense(channels // ratio, activation="relu", use_bias=False)
    dense2 = layers.Dense(channels, activation="sigmoid", use_bias=False)

    # Global Avg Pool path
    avg_pool = layers.GlobalAveragePooling2D()(input_tensor)
    avg_pool = layers.Reshape((1, 1, channels))(avg_pool)
    avg_pool = dense1(avg_pool)
    avg_pool = dense2(avg_pool)

    # Global Max Pool path
    max_pool = layers.GlobalMaxPooling2D()(input_tensor)
    max_pool = layers.Reshape((1, 1, channels))(max_pool)
    max_pool = dense1(max_pool)
    max_pool = dense2(max_pool)

    # Add and apply
    channel_attention = layers.Add()([avg_pool, max_pool])
    channel_attention = layers.Activation("sigmoid")(channel_attention)
    x = layers.Multiply()([input_tensor, channel_attention])

    # 2. Spatial Attention Module
    # Average Pool along channels
    avg_pool = tf.reduce_mean(x, axis=channel_axis, keepdims=True)
    # Max Pool along channels
    max_pool = tf.reduce_max(x, axis=channel_axis, keepdims=True)

    spatial_concat = layers.Concatenate(axis=channel_axis)([avg_pool, max_pool])
    spatial_attention = layers.Conv2D(1, (7, 7), padding="same", activation="sigmoid")(
        spatial_concat
    )

    output = layers.Multiply()([x, spatial_attention])
    return output


def train_phase8_uncertainty():
    print("--- Loading Labeled Data ---")
    try:
        X_train = np.load("X_train.npy")
        X_test = np.load("X_test.npy")
        y_train = np.load("y_train.npy")
        y_test = np.load("y_test.npy")
        print(f"Loaded Labeled X_train: {X_train.shape}, y_train: {y_train.shape}")
    except Exception as e:
        print(f"Error loading data: {e}")
        return

    # Reshape
    X_train = X_train.reshape((-1, 60, 60, 1))
    X_test = X_test.reshape((-1, 60, 60, 1))

    # --- Self-Training: Data Expansion ---
    print("\n--- Self-Training: Generating Pseudo-Labels ---")
    teacher_path = "phase7_model.h5"
    if not os.path.exists(teacher_path):
        print(f"Error: Teacher model {teacher_path} not found.")
        return

    teacher = models.load_model(teacher_path)

    # Load Unlabeled Data
    print("Loading Unlabeled Data chunk...")
    try:
        # Load a chunk or re-load the pkl
        df = pd.read_pickle("LSWMD.pkl")
        # Filter unlabeled
        df = df[df["failureType"].apply(lambda x: len(x) == 0)]
        unlabeled_samples = df["waferMap"].values
        print(f"Total Unlabeled: {len(unlabeled_samples)}")

        # Sample 20,000 NEW images (random seed different from Phase 4 if you want different ones)
        # Just random shuffle
        indices = np.random.choice(len(unlabeled_samples), 20000, replace=False)
        sample_maps = unlabeled_samples[indices]

        # Resize
        X_unlabeled = []
        for wm in sample_maps:
            resized = cv2.resize(wm, (60, 60), interpolation=cv2.INTER_NEAREST)
            X_unlabeled.append(resized)
        X_unlabeled = np.array(X_unlabeled)

        # Resize/Normalize
        X_unlabeled = X_unlabeled.astype("float32") / 2.0
        X_unlabeled = X_unlabeled.reshape((-1, 60, 60, 1))

        print(f"Unlabeled Set Prepared: {X_unlabeled.shape}")

        # Predict with Teacher
        probs = teacher.predict(X_unlabeled, batch_size=64, verbose=1)

        # Entropy Filter
        entropy = -np.sum(probs * np.log(probs + 1e-9), axis=1)
        confidence = np.max(probs, axis=1)
        pseudo_labels = np.argmax(probs, axis=1)

        # Select high quality samples
        mask = (confidence > 0.95) & (entropy < 0.2)
        X_pseudo = X_unlabeled[mask]
        y_pseudo = pseudo_labels[mask]

        print(f"Selected {len(X_pseudo)} high-confidence samples out of 20,000.")

        # Combine
        X_expanded = np.concatenate([X_train, X_pseudo], axis=0)
        y_expanded = np.concatenate([y_train, y_pseudo], axis=0)

        print(f"Expanded Dataset Size: {X_expanded.shape[0]}")

    except Exception as e:
        print(f"Error in pseudo-labeling: {e}")
        return

    # Recalculate Weights for Expanded Data
    unique_classes = np.unique(y_expanded)
    class_weights = class_weight.compute_class_weight(
        class_weight="balanced", classes=unique_classes, y=y_expanded
    )
    class_weight_dict = dict(zip(unique_classes, class_weights))
    print("Recalculated Class Weights:")
    for cls, weight in class_weight_dict.items():
        print(f"Class {cls}: {weight:.4f}")

    # --- Student Model (CBAM-CNN) ---
    print("\n--- Building Student CBAM-CNN ---")
    inputs = layers.Input(shape=(60, 60, 1))

    # Block 1
    x = layers.Conv2D(32, (3, 3), padding="same", activation="relu")(inputs)
    x = cbam_block(x)  # Attention
    x = layers.MaxPooling2D((2, 2))(x)

    # Block 2
    x = layers.Conv2D(64, (3, 3), padding="same", activation="relu")(x)
    x = cbam_block(x)  # Attention
    x = layers.MaxPooling2D((2, 2))(x)

    # Block 3
    x = layers.Conv2D(128, (3, 3), padding="same", activation="relu")(x)
    x = cbam_block(x)  # Attention
    x = layers.MaxPooling2D((2, 2))(x)

    # Classifier
    x = layers.Flatten()(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(9, activation="softmax")(x)

    student_model = models.Model(inputs, outputs)
    student_model.summary()

    # --- Training ---
    print("\n--- Training Student Model ---")
    optimizer = keras.optimizers.Adam(learning_rate=0.001)
    student_model.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )

    history = student_model.fit(
        X_expanded,
        y_expanded,
        epochs=25,
        batch_size=64,
        validation_data=(X_test, y_test),
        class_weight=class_weight_dict,
    )

    # --- Evaluation ---
    model_path = "phase8_cbam_model.h5"
    student_model.save(model_path)
    print(f"Model saved to {model_path}")

    # Metrics
    loss, acc = student_model.evaluate(X_test, y_test, verbose=0)
    print(f"\n--- Final Test Accuracy: {acc * 100:.2f}% ---")

    y_pred = np.argmax(student_model.predict(X_test), axis=1)
    cm = confusion_matrix(y_test, y_pred)

    # Scratch Recall
    scratch_recall = cm[7, 7] / np.sum(cm[7, :])
    print(f"Scratch Recall: {scratch_recall * 100:.2f}%")

    # Plot CM
    plt.figure(figsize=(10, 8))
    labels = [
        "Center",
        "Donut",
        "Edge-Loc",
        "Edge-Ring",
        "Loc",
        "Near-full",
        "Random",
        "Scratch",
        "none",
    ]
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Greens", xticklabels=labels, yticklabels=labels
    )
    plt.title(
        f"CBAM-CNN Confusion Matrix\nAcc: {acc * 100:.1f}% | Scratch Recall: {scratch_recall * 100:.1f}%"
    )
    plt.savefig("phase8_cm.png")
    print("CM saved to phase8_cm.png")


if __name__ == "__main__":
    train_phase8_uncertainty()
